# Generated by Django 3.0 on 2021-11-22 13:34

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='prerequisites',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
